train_path: 'xxxxx'
dev_path: 'xxxxx'
test_path: 'xxxxx'
vocab_path: 'xxxxx'
log_path: 'xxxxx'
save_path: 'xxxxx'
load_path: 'xxxxx'
device: 'cuda'
epochs: 100
lr: 0.0001
batch_size: 1024
emb_size: 512
hidden_size: 512
encoder_layer_num: 3
dropout: 0.2
bidirectional: True
max_len: 100
seed: 1